// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-7JapmjWMQ2EfVJxNu2AdRuJjgIHrAtQ',
    appId: '1:919136245115:web:a44d492225559bb1aad9de',
    messagingSenderId: '919136245115',
    projectId: 'love-kush-pos',
    authDomain: 'love-kush-pos.firebaseapp.com',
    storageBucket: 'love-kush-pos.firebasestorage.app',
    measurementId: 'G-DSR7BZ0PL5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1qGHRZjnGCY9J5nrPP8viMa1g8ZqtyW0',
    appId: '1:919136245115:android:1815e7e26dbfe477aad9de',
    messagingSenderId: '919136245115',
    projectId: 'love-kush-pos',
    storageBucket: 'love-kush-pos.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqGP5e7i6kJPW2fB6scncTSPrdFvYSgOw',
    appId: '1:919136245115:ios:b94dd0ab10ee4cfbaad9de',
    messagingSenderId: '919136245115',
    projectId: 'love-kush-pos',
    storageBucket: 'love-kush-pos.firebasestorage.app',
    iosBundleId: 'com.lovekush.lovekushPos',
  );
}
